lavalink:
    plugins:
        - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
          repository: https://maven.topi.wtf/releases
        - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.0.1
          repository: https://maven.topi.wtf/releases
        - dependency: "com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.0"
          repository: "https://maven.lavalink.dev/releases"
        - dependency: "com.dunctebot:skybot-lavalink-plugin:1.6.3"
          repository: "https://maven.lavalink.dev/releases"
    server:
        bufferDurationMs: 400
        frameBufferDurationMs: 5000
        gc-warnings: true
        opusEncodingQuality: 0
        password: Mewwme
        playerUpdateInterval: 5
        resamplingQuality: LOW
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: true
            mixer: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: true
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        max-history: 30
        max-size: 1GB
    level:
        lavalink: INFO
        root: INFO
    path: ./logs/
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    dunctebot:
        ttsLanguage: en-AU
        sources:
      # true = source enabled, false = source disabled
          getyarn: true # www.getyarn.io
          clypit: true # www.clyp.it
          tts: true # speak:Words to speak
          pornhub: true # should be self-explanatory
          reddit: true # should be self-explanatory
          ocremix: true # www.ocremix.org
          tiktok: true # tiktok.com
          mixcloud: true # mixcloud.com
          soundgasm: true # soundgasm.net
    lavasrc:
        deezer:
            masterDecryptionKey: fr78257e1e5251fb1a6d3590847031db
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1
            translate: false
            voice: default voice
        providers:
            - ytsearch:"%ISRC%"
            - ytmsearch:%QUERY%
            - ytsearch:%QUERY%
            - scsearch:%QUERY%
            - dzisrc:%ISRC%
            - dzsearch:%QUERY%
        sources:
            applemusic: false
            deezer: true
            flowerytts: true
            spotify: true
            yandexmusic: true
            youtube: true
        spotify:
            albumLoadLimit: 50
            clientId: fdf0e2d1da9e40169b5918f73addae04
            clientSecret: db0fa34ff766490e87e9996c0ae844e0
            countryCode: ID
            playlistLoadLimit: 100
        yandexmusic:
            accessToken: y0_AgAAAABy4jt2AAG8XgAAAAD1KXSLeEPG32D5Q26qC8QbNoIRdaVFS3E
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    port: 2333
